# Site settings
title: Pouya Zare
description: 'Personal Card Page'
url: 'http://pzare555.github.io'
baseurl: ''
profilepic: '/images/pouyazare.png'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'js/fa.min.js'

author:
  name: 'Pouya Zare'
  email: pouya.zare.1680@gmail.com
  github_username:  pzare555
  instagram_username: pouya_graphics_zare

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
